# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 18310be2bd099343493f9fca1674565d2ddf880b53a16d1e0f7509705549d49762c0916cc9d62b712de92bf9507ea6b23e0d9b064915cfde39d74674dd1d28bf

test:
  secret_key_base: b9cd4659018cbaf402f17443f34926e480af93f743145e80d7576c6f0a74bd8dc0e10ef19d81261f15dc164c742a44e7874ac43637d8f42e422b6e7695142de3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
